name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Confirmation to proceed with infrastructure destruction'
        required: true
        default: 'false'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan infrastructure destruction
        run: terraform plan -destroy

      - name: Confirm infrastructure destruction
        if: ${{ github.event.inputs.confirmation == 'true' }}
        env: 
          TF_LOG: DEBUG # You can set this to TRACE for even more verbose logs
        run: terraform destroy -auto-approve

      - name: Destroy all S3 buckets and DynamoDB tables
        run: |
          # Delete all S3 buckets
          for bucket in $(aws s3api list-buckets --query 'Buckets[*].Name' --output text); do
            aws s3 rb "s3://${bucket}" --force
          done
      
          # Delete all DynamoDB tables
          for table in $(aws dynamodb list-tables --query 'TableNames' --output text); do
            aws dynamodb delete-table --table-name "${table}"
          done
      